REF_LEFT_SUPPORT_THRESHOLD = 0
REF_RIGHT_SUPPORT_THRESHOLD = 0
REF_LEFT_JUNCTION_THRESHOLD = 0
REF_RIGHT_JUNCTION_THRESHOLD = 0

NONREF_LEFT_SUPPORT_THRESHOLD = 0
NONREF_RIGHT_SUPPORT_THRESHOLD = 0
NONREF_LEFT_JUNCTION_THRESHOLD = 0
NONREF_RIGHT_JUNCTION_THRESHOLD = 0